  
name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
